### PR TITLE
Improvement: utilize environment variable for paths

### PR DESCRIPTION
**Pull request by ttytm**
Thanks a for your work @ArtemkaKun 🚀! I will certainly use a lot of it in some upcoming V projects 🙂

The PR utilizes an environment variable for the runner work path. If someone wants to use the action it's just one place that needs to be changed then. It also makes it a little less prone to typos in the path and more concise.

### CODE REVIEW

**Comment by ttytm** [comment]
There is one thing I'm noticing when I try to use the action. 
You won't run into this because your V installation is always restored from cache as it looks.

When using the `setup-v` action it's always failing when a version is specified:
```
Run vlang/setup-v@v1.3
Resolved  as weekly.2023.08
Downloading vlang weekly.2023.08...
Creating directory: /home/runner/work/v-test/v-test/vlang/vlang_linux_x64
Downloading the archive
Downloaded archive 'https://codeload.github.com/vlang/v/legacy.tar.gz/refs/tags/weekly.2023.08'
Writing archive to disk
Extracting the archive
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/v-test/v-test/vlang/vlang_linux_x64/4d2[9](https://github.com/tobealive/v-test/actions/runs/4778371619/jobs/8494753360#step:3:10)43d3-eaf3-49[12](https://github.com/tobealive/v-test/actions/runs/4778371619/jobs/8494753360#step:3:13)-81e8-4aab43bda48b -f /home/runner/work/v-test/v-test/vlang/vlang_linux_x64/4d2943d3-eaf3-4912-81e8-4aab43bda48b.tar.gz
Resolved version vlang-v-096065f
Running make...
vlib/rand/rand.v:447:39: warning: variable `it` in array initialization will soon be replaced with `index`
Error: Command failed: make
```

This also happens when i specify a newer version, i.E. weekly.2023.15.
Installation works when removing the version.

This looks like an upstream issue with `setup-v` to me.

**Comment by ttytm** [comment]
Looks like running the CI on a PR that doesn't has cache access runs just into this mentioned issue.

**Comment by ArtemkaKun** [comment]
Hi, thanks for the PR. Cache on GitHub Actions is removed automatically after some time of no usage. So we should fix `v-setup` error anyway (or don't use the cache, which is probably not the best solution right now)

**Comment by ArtemkaKun** [comment]
The one workaround we could use - is to not specify the version and build the latest commit every time, cache it, and then use `version` output from `v-setup` as key for cache label

**Comment by ttytm** [comment]
Yep sounds good. The installation takes about 20 seconds so it's totally reasonable

**Comment by ArtemkaKun** [comment]
I will merge this PR since it seems to be legit and will introduce that `v-setup` workaround in a few hours

**Comment by ttytm** [comment]
Thanks. PR was tested on a private repo before submitting it. Also I just used the setup from latest commit and ci was green 👍

Screenshot_20230423_165427

**Pull request merged**
