### PR TITLE
Fix V installation

### PR DESCRIPTION
**Pull request by ArtemkaKun**

### CODE REVIEW

**Comment by ArtemkaKun** [comment]
@tobealive I do a quick fix for V installation problem - now it will install the latest commit from the main branch. I also improved your change so user don't need to change project name at all - it will be automatically retrieved from GitHub Actions variables

**Comment by ttytm** [comment]
Very nice, especially the improvement with automatic retrieval!

What I've noticed is that it might be worth to still keep caching. The consecutive install steps are reduced to 1s then.

**Comment by ttytm** [comment]
Since the installation doesn't take long and V is as you commented rapidly changing it's also okay without. Just wanted to leave this as a note.

**Comment by ArtemkaKun** [comment]
Aaa, right. O wanted it to be done so quickly that I didn't think about that one possibility. I will do it rn

**Comment by ttytm** [comment]
Cache key could be based on project version when v is more ripe.

```
key: ${{ runner.os }}-v-${{ hashFiles('**/v.mod') }}
```

Until then maybe something like:
```
echo "V_VERSION=$(v -v)" >> $GITHUB_ENV
```
And use the `env.V_VERSION` in the key.
Inspired by what you suggested in the last PR :).

**Comment by ArtemkaKun** [comment]
> Cache key could be based on project version when v is more ripe.
> 
> ```
> key: ${{ runner.os }}-v-${{ hashFiles('**/v.mod') }}
> ```
> 
> Until then maybe something like:
> 
> ```
> echo "V_VERSION=$(v -v)" >> $GITHUB_ENV
> ```
> 
> And use the V_VERSION in the key.

Nice idea with `hashFiles('**/v.mod')`, but I think for now I just stop on `echo "V_VERSION=$(v -v)" >> $GITHUB_ENV` where instead of `v -v` I will use `${{ steps.install-v.outputs.version }}`

**Comment by ArtemkaKun** [comment]
Hmm, I thought that V with `check-last: true` will have a version of commit, but it has just `0.3.3`

**Comment by ArtemkaKun** [comment]
Now it contains the commit ID, thanks @tobealive for the good help with that V_VERSION code ❤️

**Comment by ttytm** [comment]
Checking on the version that's installed despite `check-last: true` it's not latest commit. ~~Looks fairly old~~:
https://api.github.com/repos/vlang/v/commits/d8167b8

Sorry all cool. Was confused with something else about the date.

**Comment by ArtemkaKun** [comment]
> Checking on the version that's installed despite `check-last: true` it's not latest commit. ~Looks fairly old~: https://api.github.com/repos/vlang/v/commits/d8167b8
> 
> Sorry all cool. Was confused with something else about the date.

I install the latest commit, just `version` output variable contains only X.Y.Z version. Anyway, this change merged

**Comment by ttytm** [comment]
Yep `${{ steps.install-v.outputs.version }}` is 0.3.3. `v -v` has the commit. But thought the commit sha is dated when it wasn't.

**Comment by ttytm** [comment]
And good work. Thanks a lot!

**Pull request merged**
